module.exports = {
    PORT: 1515,
    errors: {
        ANSWER_NOT_FOUND: 'Answer not found',
        BLOG_NOT_FOUND: 'Blog Not Found',
        COMMENT_NOT_FOUND: 'Comment not found',
        CRAWLER_NOT_FOUND: 'Crawler not found',
        NOTIFICATION_NOT_FOUND: 'Notification Not Found',
        POST_NOT_FOUND: 'Post Not Found',
        DRAFT_NOT_FOUND: 'Draft Not Found',
        QUESTION_NOT_FOUND: 'Question not found',
        TOPIC_NOT_FOUND: 'Topic Not Found',
        UNAUTHORIZED: 'UNAUTHORIZED',
        USER_NOT_FOUND: 'User Not Found',
        INCORRECT_EMAIL_CATEGORY: 'INCORRECT_EMAIL_CATEGORY',
    },
    scores: {
        NEW_ANSWER: 5,
        UPVOTE_ANSWER: 1,
        DOWNVOTE_ANSWER: 0,
        NEW_POST: 7,
        UPVOTE_POST: 1,
        DOWNVOTE_POST: 0,
        NEW_COMMENT: 0,
        UPVOTE_COMMENT: 0,
        DOWNVOTE_COMMENT: 0,
    },
    notificationTypes: {
        QUESTION_NOTIFICATION: 'Question',
        ANSWER_NOTIFICATION: 'Answer',
        COMMENT_NOTIFICATION: 'Comment',
        POST_NOTIFICATION: 'Post',
        USER_NOTIFICATION: 'User',
    },
};
